from typing import Protocol, runtime_checkable


@runtime_checkable
class CharStream(Protocol):
    """Port do domínio — abstrai a fonte de caracteres."""

    def has_next(self) -> bool: ...
    def next(self) -> str: ...
    def peek(self) -> str: ...
    def rewind(self) -> None: ...
    def current_line(self) -> int: ...
