from enum import Enum


class AtomCode(str, Enum):
    # Categoria A — identificadores e literais
    IDENTIFIER = "A01"
    INTEGER_LIT = "A02"
    REAL_LIT = "A03"
    SCIENTIFIC_LIT = "A04"
    STRING_LIT = "A05"
    CHAR_LIT = "A06"

    # Categoria B — palavras reservadas
    PROGRAM = "B01"
    END_PROGRAM = "B02"
    DECLARATIONS = "B03"
    END_DECLARATIONS = "B04"
    FUNCTIONS = "B05"
    END_FUNCTIONS = "B06"
    FUNC_TYPE = "B07"
    VAR_TYPE = "B08"
    PARAM_TYPE = "B09"
    REAL_KW = "B10"
    INTEGER_KW = "B11"
    STRING_KW = "B12"
    BOOLEAN_KW = "B13"
    CHARACTER_KW = "B14"
    VOID_KW = "B15"
    IF_LOWER = "B16"
    IF_UPPER = "B17"
    ELSE = "B18"
    END_IF = "B19"
    WHILE = "B20"
    END_WHILE = "B21"
    RETURN = "B22"
    BREAK = "B23"
    PRINT = "B24"
    TRUE = "B25"
    FALSE = "B26"

    # Categoria C — símbolos e operadores
    ASSIGN = "C01"
    COLON = "C02"
    SEMICOLON = "C03"
    LPAREN = "C04"
    RPAREN = "C05"
    LBRACKET = "C06"
    RBRACKET = "C07"
    LBRACE = "C08"
    RBRACE = "C09"
    LE = "C10"
    LT = "C11"
    GT = "C12"
    GE = "C13"
    EQ = "C14"
    NEQ = "C15"
    HASH = "C16"
    PLUS = "C17"
    MINUS = "C18"
    STAR = "C19"
    SLASH = "C20"
    PERCENT = "C21"
    COMMA = "C22"
    QUESTION = "C23"
    ARRAY_DECL = "C24"

    # Especial
    EOF = "D01"
